### ISSUE TITLE
Use "null" literal instead of exceptions

### ISSUE THREAD

**Issue by dawrut** [nokia-wroclaw/innovative-project-jackdaw#18]
It's way too harsh to throw an exception on simple value mappings (please refer to refs below). I think literal "null" should do fine for default case in the switch statement since null is a valid JSON value.

https://github.com/nokia-wroclaw/innovative-project-jackdaw/blob/0d4aa0e17ab3985930176d3782c25f0b447d42be/flightdata-kafka-consumer/src/main/java/com/jackdaw/consumer/JSONSerializer.java#L86

https://github.com/nokia-wroclaw/innovative-project-jackdaw/blob/0d4aa0e17ab3985930176d3782c25f0b447d42be/flightdata-kafka-consumer/src/main/java/com/jackdaw/consumer/JSONSerializer.java#L105

**Comment by dawrut** [comment]
I see it's used for JSON objects so instead of Optional, the default case could be "null" literal since it is a valid JSON value

**Comment by mnajda** [comment]
Done in cfc36e8, on pull request #17
