### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by dawrut** [nokia-wroclaw/innovative-project-jackdaw#24]
There are plenty of magic numbers in the producer class.

Please do refactor, example resources:
http://www.thinkcode.se/blog/2011/07/28/magic-numbers
https://sourcemaking.com/refactoring/replace-magic-number-with-symbolic-constant

**Comment by KacperBieganek** [comment]
Issues #22, #23 and #24 have been adressed on producer-refactor branch.
