### ISSUE TITLE
Types as enumerations

### ISSUE THREAD

**Issue by dawrut** [nokia-wroclaw/innovative-project-jackdaw#25]
All `is*Valid` methods define string arrays for a corresponding type. These should be represented as enumerations, whatmore, they exist but are not used, [example](https://github.com/nokia-wroclaw/innovative-project-jackdaw/blob/master/flightdata-kafka-producer/src/main/java/com/jackdaw/avro/flights/FlightType.java).

Please refactor code to use enumeration types.

**Comment by mnajda** [comment]
Can you be more specific or provide example in code?

**Comment by KacperBieganek** [comment]
Those methods exists because when we load data from the file all we have is a string. I've created those methods to make sure we will not get any unwanted exceptions while using method valueOf which changes specific strings into enums which have same specified name.

**Comment by KacperBieganek** [comment]
So i can change those methods to be like
```java
boolean is*Valid(String str){
    try{
        Flight*.valueOf(str)
    } catch (IllegalArgumentException e){
        return false;
    }
    return true;
}
```
Or remove those methods and refactor code to do validation while creating new `Flight` object in `createFlight` method using `try-catches` there
```

**Comment by dawrut** [comment]
Motivation is fine, the problem comes that you have two places for definition of same in different types. 

There are many possible solutions, including the one above but it's rather heavy. You can also define a helper class/method.

I would suggest to use commons-lang3, in this specific case, this [one](https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/EnumUtils.html#isValidEnum(java.lang.Class,%20java.lang.String)).

Example usage:
```java
private boolean isFlightSituationValid(String situation) {
        return EnumUtils.isValidEnum(FlightSituation.class, situation);
}
```
