### ISSUE TITLE
Return Option instead of throwing an exception

### ISSUE THREAD

**Issue by dawrut** [nokia-wroclaw/innovative-project-jackdaw#29]
`createFlight` throws exceptions when a single line is invalid and stops the application.

Please refactor code to apply a `Option` return type.

https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html
http://www.baeldung.com/java-optional

Please use more liberal number conversion approach as well:
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/math/NumberUtils.html

**Comment by KacperBieganek** [comment]
All the new issues have been addressed, so if you might doing a review for my pull request to check if they meet your expectations.
